<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
        <!-- CSRF Token -->
        <meta name="csrf-token" content="{{ csrf_token() }}">
        <title>Términos y condiciones</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootswatch/4.3.1/cerulean/bootstrap.min.css">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/material-design-icons/3.0.1/iconfont/material-icons.min.css">
         <!-- Styles -->
        <link href="{{ asset('assets/css/styles.min.css?h=28f8fc1429469e8e064612799b42de09') }}" rel="stylesheet">
        <link href="{{ asset('assets/fonts/fontawesome5-overrides.min.css?h=03ab36d1dde930b7d44a712f19075641') }}" rel="stylesheet">
        <link href="{{ asset('assets/alertifyjs/css/alertify.min.css') }}" rel="stylesheet">
        <link href="{{ asset('assets/alertifyjs/css/themes/bootstrap.min.css') }}" rel="stylesheet">
        
    </head>    
    <body>
        <div style="padding-top: 40px;padding-right: 20px;padding-bottom: 20px;padding-left: 20px;"><span class="text-justify" style="font-size: 12px;">CONVENIO DE LIBERACION DE RESPONSABILIDAD QUE SE CELEBRA POR PARTE DE KIDS CLUB Y POR OTRA PARTE LA PERSONA QUE FIGURA EN LA CARATULA DE ESTE DOCUMENTO, AL TENOR DE LAS SIGUIENTES DECLARACIONES Y CLAUSULAS.<br /><br /><strong>D E C L A R A C I O N E S</strong><br /><br />I. DECLARA KIDS CLUB QUE CUENTA CON LA CAPACIDAD TECNICA Y PROFESIONAL ASI COMO LOS RECURSOS Y MATERIALES NECESARIOS PARA CUMPLIR EL OBJETIVO.<br /><br />II. DECLARA EL PARTICIPANTE QUE SUS DATOS GENERALES, SON LOS QUE APARECEN EN LA CARATURLA DE ESTE DOCUMENTO, CONOCE Y ENTIENDE EL ALCANCE LEGAL DE ESTE DOCUMENTO Y SU CONTENIDO.<br /><br />III. AMBAS PARTES DECLARAN QUE SE RECONOCEN LA PERSONALIDAD Y CAPACIDAD CON LA QUE CMPARECEN A CELEBRACION DEL PRESENTE DOCUMENTO, LIBRES CUALQUIER DOLO ASI COMO LAS SIGUIENTES<br /><br /><strong>C L A U S U L A S</strong><br /><br />I. EL PARTICIPANTE O TUTOR, LIBERA A KIDS CLUB DE CUALQUIER RESPONSABILIDAD INHERENTE A SU PARTICIPACION EN LOS JUEGOS Y ACTIVIDADES QUE SE REALICEN DENTRO DE LAS INSTALACIONES, POR LO QUE DESDE ESTE MOMENTO RECUNCIA A CUALQUIER DERECHO A RECLAMAR, DEMANDAR O DENUNCIAR CUALQUIER DAÑO O AFECTACION DE CUALQUIER INDOLE QUE PUEDA RESENTIR TOTAL O PARCIALMENTE POR SU PARTICIPACION EN LOS JUEGOS (TRAMPOLIN Y RESBALADILLA) ASI COMO ACTOS U OMISIONES DE KIDS CLUB.<br /><br />II. EL PARTICIPANTE O TUTOR, ASUME Y ACEPTA TODOS LOS RIESGOS EXISENTES DENTRO DE LAS INSTALACIONES DE KIDS CLUB TALES COMO ( CORTADURAS, CONTUNCIONES, LUXACIONES, FRACTURAS DE HUESOS U OTRAS LESIONES GRAVES QUE SE PUEDEN OCASIONAR USANDO LAS INSTALCIONES ) LA INTERVENCION DEL PARTICIPANTE A ESTAS ACTIVIDADES ES VOLUNTARIA. ELIGIENDO A PARTICIPAR A PESAR DE CONOCER LOS RIESGOS DE LAS MISMAS.<br /><br />III. EL PARTICIPANTE O TUTOR MANIFIESTA BAJO PROTESTA DE DECIR VERDAD QUE TIENE UNA POLIZA DE SEGUROS DE GASTOS MEDICOS CON COBERTURA AMPLIA, SUFICIENTE PARA ATENDER CUALQUIER LESION O DAÑO QUE PUDIERA CAUSARSE, POR LO QUE ACEPTA HACERSE CARGO, DE MANERA DIRECTA, POR TODOS LOS COSTOS QUE SE GENERAN POR DICHA LESION O DAÑO. ACEPTANDO EXPRESAMENTE QUE ASUME EL RIESGO DE LOS PROCEDIMENTOS MEDICOS O FISICOS QUE PUDIERA PADECER.<br /><br />IV. AVISO DE PRIVACIDAD. KIDS CLUB CON DIRECCION: AV. ING. EDUARDO MOLINA 1623 COL. EL COYOL, GUSTAVO A. MADERO, 07420 CUIDAD DE MEXICO, UTILIZARA SUS DATOS PERSONALES UNICA Y EXCLUSIVAMENTE PARA BRINDARLE NUESTROS SERVICIOS DE ENTRETENIMIENTO, EVENTOS INFANTILES Y PUBLICIDAD.<br /><br />V. EL PARTICIPANTE O TUTOR RECONOCE QUE HA LEIDO, ENTENDIDO Y COMPRENDIDO A PLENITUD LA TOTALIDAD DE ESTE DOCUMENTO Y QUE ESTA DE ACUERDO CON SU CONTENIDO.<br /><br />AV. ING. EDUARDO MOLINA 1623 COL. EL COYOL, GUSTAVO A. MADERO, 07420 CUIDAD DE MEXICO (PLAZA ORIENTE)</span></div>
    </body>      
</html>
